# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Anand Mayakonda
title: Bioinformatics and Cancer Genomics
email: anandmt3@gmail.com
website: https://poisonalien.github.io/

# Social links
twitter_username: anand_mt
github_username: poisonalien
orcid_username: 0000-0003-1162-687X
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
linkedin_username: anand-mayakonda-538a4617b
darkmode: true
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hello there! Thank you for visiting my resume. I am Anand and, I am a Post-doc working on **Genomics and Epigenomics** genomics of myeloid and lymphoid malignancies.
  My research interests are in the biology of leukemia, MRD, clonal evolution, and PROTACs. Technically, I am most skilled in <mark>R</mark>, some of <mark>Python</mark> and <mark>Rust</mark>.

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in Academic research you can also find me on [Biostars](https://www.biostars.org/u/6030/). My other hobbies are, 
   - Reading: checkout my bookshelf on [goodreads](https://www.goodreads.com/user/show/84549956-anand-mayakonda)
   - Running: checkout my runs on [strava](https://www.strava.com/athletes/62414122)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
